## **Module 2: Advanced Array Operations**

### **Key Learning Objectives**
- Deepen understanding of NumPy arrays.
- Perform reshaping, concatenation, and splitting of arrays.
- Understand broadcasting and apply it effectively.
- Perform advanced indexing, including boolean and fancy indexing.
- Manipulate array shapes and dimensions.

---

## **Module 2: Advanced Array Operations**

### **1. Reshaping Arrays**

#### **Concepts to Learn**
Reshaping is the process of changing the dimensions of an array. It’s useful when handling data in different formats, such as converting a 1D array to a matrix or vice versa.

#### **Scenarios**
- Converting a flat dataset into a grid for image processing.
- Rearranging time-series data into windowed segments.

#### **Examples**

In [3]:
import numpy as np
# Example 1: Reshaping a 1D array into a 2D matrix
data = np.arange(1, 13)  # 1D array with 12 elements
matrix = data.reshape(3, 4)  # Reshape to 3 rows, 4 columns
print("Reshaped matrix:\n", matrix)

Reshaped matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [4]:
# Example 2: Flattening a matrix back to a 1D array
flattened = matrix.flatten()
print("Flattened array:", flattened)

Flattened array: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [13]:
# Example 3: Reshaping to a higher dimension
cube = data.reshape(2, 3, 2)  # 3D array
print("Reshaped to 3D:\n", cube)

Reshaped to 3D:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


#### **Exercises**
1. Create a 1D array of 20 elements and reshape it into a 5x4 matrix.
2. Convert the reshaped matrix back into a 1D array using `ravel()`.
3. Reshape a 2D array into a 3D array for a scenario like processing image frames.

---

### **2. Joining and Splitting Arrays**

#### **Concepts to Learn**
Joining combines multiple arrays into one, while splitting divides an array into smaller parts.

#### **Scenarios**
- Merging datasets (e.g., concatenating rows of data from two files).
- Dividing a large dataset for parallel processing.

#### **Examples**

In [14]:
# Joining Arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
joined = np.concatenate((array1, array2))
print("Joined array:", joined)

Joined array: [1 2 3 4 5 6]


In [15]:
# Vertical stacking
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
vstacked = np.vstack((matrix1, matrix2))
print("Vertically stacked:\n", vstacked)

Vertically stacked:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [16]:
# Splitting Arrays
matrix = np.arange(16).reshape(4, 4)  # 4x4 matrix
split = np.hsplit(matrix, 2)  # Split into two 2x4 matrices
print("Split result:")
for part in split:
    print(part)

Split result:
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


#### **Exercises**
1. Concatenate two 1D arrays and then reshape the result into a matrix.
2. Split a 6x6 matrix into four 3x3 sub-matrices.
3. Stack three 1D arrays vertically.

### **3. Broadcasting**

#### **Concepts to Learn**
Broadcasting allows arithmetic operations between arrays of different shapes by "stretching" the smaller array.

#### **Scenarios**
- Adding a constant to all pixels in an image.
- Normalizing rows in a dataset by subtracting the mean.

#### **Examples**

In [17]:
# Example 1: Broadcasting a scalar
matrix = np.array([[1, 2], [3, 4]])
result = matrix + 10  # Adds 10 to all elements
print("After broadcasting scalar:\n", result)

After broadcasting scalar:
 [[11 12]
 [13 14]]


In [18]:
# Example 2: Broadcasting a 1D array across rows
row_means = np.array([1, 2])  # Shape (2,)
broadcast_result = matrix - row_means
print("Row-wise broadcast:\n", broadcast_result)

Row-wise broadcast:
 [[0 0]
 [2 2]]


In [19]:
# Example 3: Broadcasting with higher dimensions
array1 = np.array([[1], [2], [3]])  # Shape (3, 1)
array2 = np.array([10, 20, 30])  # Shape (3,)
broadcast_result = array1 + array2
print("Broadcasting with higher dimensions:\n", broadcast_result)

Broadcasting with higher dimensions:
 [[11 21 31]
 [12 22 32]
 [13 23 33]]


#### **Exercises**
1. Add a scalar to a 2D array using broadcasting.
2. Multiply a column vector by a row vector using broadcasting to create a matrix.
3. Subtract the mean of each row from a 3x3 matrix using broadcasting.

---

### **4. Advanced Indexing**

#### **Concepts to Learn**
- **Boolean Indexing:** Use conditions to filter elements.
- **Fancy Indexing:** Use arrays of indices to select elements.

#### **Scenarios**
- Filtering data that meets certain conditions (e.g., values > threshold).
- Selecting specific rows or columns.

#### **Examples**

In [20]:
# Boolean Indexing
data = np.array([10, 15, 20, 25, 30])
filtered = data[data > 20]  # Select elements greater than 20
print("Filtered data:", filtered)

# Fancy Indexing
matrix = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
rows = [0, 2]
cols = [1, 2]
selected = matrix[rows, cols]  # Select (0, 1) and (2, 2)
print("Fancy indexing result:", selected)

Filtered data: [25 30]
Fancy indexing result: [20 90]


#### **Exercises**
1. Use boolean indexing to filter numbers divisible by 3 from a 1D array.
2. Extract diagonal elements of a 4x4 matrix using fancy indexing.
3. Use fancy indexing to select non-contiguous rows and columns from a 3x3 matrix.

---

### **5. Manipulating Dimensions**

#### **Concepts to Learn**
- Adding or removing dimensions to match desired shapes.
- Combining arrays into higher-dimensional structures.

#### **Scenarios**
- Preparing data for machine learning models (e.g., adding a batch dimension).
- Stacking time-series data.

#### **Examples**

In [21]:
# Adding Dimensions
array = np.array([1, 2, 3])
row_vector = np.expand_dims(array, axis=0)  # Row vector
col_vector = np.expand_dims(array, axis=1)  # Column vector
print("Row vector:", row_vector)
print("Column vector:\n", col_vector)

Row vector: [[1 2 3]]
Column vector:
 [[1]
 [2]
 [3]]


In [22]:
# Removing Dimensions
matrix = np.array([[[1, 2, 3]]])  # Shape (1, 1, 3)
squeezed = np.squeeze(matrix)  # Remove size-1 dimensions
print("Squeezed array:", squeezed)

Squeezed array: [1 2 3]


In [23]:
# Stacking
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
stacked = np.stack((array1, array2), axis=0)  # Stack along a new axis
print("Stacked array:\n", stacked)

Stacked array:
 [[1 2 3]
 [4 5 6]]


#### **Exercises**
1. Convert a 1D array into both row and column vectors.
2. Create a batch of 3 images (2x2 matrices) by stacking three 2x2 matrices along a new axis.
3. Remove singleton dimensions from a 3D array of shape `(1, 5, 1)`.

---

### **Challenge Exercises**
1. Create a 10x10 checkerboard pattern using broadcasting and slicing techniques.
2. Generate a 4x4 matrix with random values and replace all elements greater than 0.5 with 1, and others with 0.
3. Split a 3D array into its individual 2D planes along a specific axis.