### **1. Introduction to Numerical Computing**

#### **What is Numerical Computing?**  
Numerical computing involves performing mathematical calculations and data manipulations programmatically. It is essential for tasks such as scientific simulations, data analysis, and engineering computations. Unlike symbolic computation (manipulating algebraic expressions), numerical computing works with numerical approximations, making it ideal for solving real-world problems.

#### **Why is NumPy Important?**  
- **Speed:** NumPy is built on C and Fortran, offering fast performance compared to pure Python lists.  
- **Efficiency:** It uses contiguous memory storage, leading to better memory usage and faster computation.  
- **Functionality:** Provides mathematical operations and functions optimized for arrays, which are challenging or slow with standard Python.

#### **Applications of NumPy:**  
- **Data Science:** Efficiently handling large datasets for preprocessing and analysis.  
- **Machine Learning:** Serving as the foundation for libraries like TensorFlow and PyTorch.  
- **Scientific Computing:** Simulating physical processes or solving equations.  
- **Image Processing:** Manipulating images represented as multi-dimensional arrays.

---

### **2. Getting Started with NumPy**

#### **Installing NumPy**
- Use Python’s package manager, `pip`, to install NumPy:
  ```bash
  pip install numpy
  ```
- Confirm the installation by running the following Python code:
  ```python
  import numpy as np
  print(np.__version__)
  ```
This ensures NumPy is installed correctly and shows the current version.

#### **Importing and Setting Up**  
- Standard practice is to import NumPy using the alias `np`:
  ```python
  import numpy as np
  ```
This reduces typing and follows community conventions, making your code easier to read.

#### **Understanding the ndarray Structure**  
- **ndarray (N-dimensional array):** The core data structure of NumPy, representing arrays with a fixed size and homogeneous data types (all elements must be the same type, such as integers or floats).
- **Key Features:**
  - **Homogeneous data:** Ensures consistency in computations.
  - **Contiguous memory layout:** Speeds up processing compared to Python lists.
  - **Dimensionality:** Supports multi-dimensional arrays (e.g., 1D vectors, 2D matrices, 3D tensors).

---

### **3. Basic Operations with NumPy Arrays**

#### **Creating Arrays**  
Learn how to create arrays in different ways:
- **From lists or tuples:**
  ```python
  np.array([1, 2, 3])
  ```
- **Pre-filled arrays:**  
  - Zeros:
    ```python
    np.zeros((2, 3))  # 2 rows, 3 columns
    ```
  - Ones:
    ```python
    np.ones((3, 3))
    ```
  - Empty (values depend on memory state):
    ```python
    np.empty((2, 2))
    ```
- **Using sequences:**  
  - Ranges:
    ```python
    np.arange(1, 10, 2)  # Start=1, Stop=10, Step=2
    ```
  - Linearly spaced values:
    ```python
    np.linspace(0, 1, 5)  # 5 values from 0 to 1
    ```

#### **Exploring Array Attributes**  
Understand key properties of arrays:
- **Shape:** Number of elements along each axis:
  ```python
  array.shape
  ```
- **Size:** Total number of elements:
  ```python
  array.size
  ```
- **Data type (dtype):** Type of elements (e.g., `int32`, `float64`):
  ```python
  array.dtype
  ```
- **Number of dimensions:**
  ```python
  array.ndim
  ```
- **Element size (in bytes):**
  ```python
  array.itemsize
  ```

#### **Indexing and Slicing Arrays**  
Master accessing and modifying array elements:
- **Indexing:** Access a specific element:
  ```python
  array[2, 3]  # Element in row 3, column 4 of a 2D array
  ```
- **Slicing:** Extract subarrays:
  ```python
  array[1:4, :2]  # Rows 2-4, Columns 1-2
  ```
- **Negative indexing:** Access elements from the end:
  ```python
  array[-1, -1]  # Last element of the last row
  ```

#### **Performing Basic Arithmetic**  
Perform mathematical operations directly on arrays:
- **Element-wise operations:**
  ```python
  array1 + array2
  array1 - array2
  ```
- **Scalar operations:** Apply operations with a single value:
  ```python
  array * 2
  array / 3
  ```

#### **Printing and Formatting Arrays**  
- Display arrays with better formatting:
  ```python
  print(array)
  ```
- Customize display settings:
  ```python
  np.set_printoptions(precision=2, suppress=True)  # Round to 2 decimals
  ```

---

### **Practical Exercises**

1. **Create a 1D array:**
   ```python
   np.array([1, 2, 3, 4, 5])
   ```

2. **Generate a 2D array of zeros:**
   ```python
   np.zeros((3, 4))  # 3 rows, 4 columns
   ```

3. **Extract a subarray:**
   - From a 3x3 matrix:
     ```python
     array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
     print(array[0:2, 1:3])  # Rows 1-2, Columns 2-3
     ```

4. **Perform arithmetic operations:**
   ```python
   array1 = np.array([1, 2, 3])
   array2 = np.array([4, 5, 6])
   print(array1 + array2)  # Output: [5 7 9]
   ```

5. **Explore attributes of a 2D array:**
   ```python
   array = np.array([[1, 2], [3, 4], [5, 6]])
   print(array.shape)  # (3, 2)
   print(array.size)   # 6
   print(array.dtype)  # int32
   ```

---

### Resources for Hands-On Learning
- **Interactive Notebook:** Practice in Jupyter Notebook or Google Colab.
- **Recommended Reading:** NumPy documentation and beginner-friendly tutorials.
- **Videos:** Watch NumPy introduction videos on YouTube for visual demonstrations.

### **Exercise Set 1: Installing and Importing NumPy**

#### **Step 1: Install NumPy**

In [ ]:
!pip install numpy

#### **Step 2: Import NumPy and Check Version**

In [1]:
import numpy as np

# Print version
print("NumPy version:", np.__version__)

NumPy version: 2.0.2


### **Exercise Set 2: Creating Arrays**

#### **Exercise 2.1: Create Arrays**
1. Create a 1D array of numbers 1 to 10.

In [2]:
array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(array1)

[ 1  2  3  4  5  6  7  8  9 10]


2. Create a 3x3 array filled with zeros.

In [3]:
array2 = np.zeros((3, 3))
print(array2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


3. Create a 2x4 array filled with ones.

In [4]:
array3 = np.ones((2, 4))
print(array3)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


4. Generate an array with numbers from 5 to 20 with a step of 3.

In [5]:
array4 = np.arange(5, 21, 3)
print(array4)

[ 5  8 11 14 17 20]


5. Generate an array of 6 evenly spaced numbers between 0 and 1.

In [6]:
array5 = np.linspace(0, 1, 6)
print(array5)

[0.  0.2 0.4 0.6 0.8 1. ]


### **Exercise Set 3: Array Attributes**

#### **Exercise 3.1: Explore Array Properties**
Given the following array:

In [8]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

1. Print the shape of the array.

In [9]:
print("Shape:", array.shape)

Shape: (3, 3)


2. Print the number of dimensions.

In [10]:
print("Number of dimensions:", array.ndim)

Number of dimensions: 2


3. Print the total number of elements.

In [11]:
print("Size:", array.size)

Size: 9


4. Print the data type of elements.

In [12]:
print("Data type:", array.dtype)

Data type: int64


5. Print the size in bytes of each element.

In [13]:
print("Element size (bytes):", array.itemsize)

Element size (bytes): 8


### **Exercise Set 4: Indexing and Slicing**

#### **Exercise 4.1: Access Specific Elements**
1. Create a 3x3 array:

In [16]:
import numpy as np
array = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(array)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [17]:
# Access the following elements:
# Element at row 2, column 3:
print(array[1, 2])

60


In [18]:
# Element at row 3, column 1:
print(array[2, 0])

70


#### **Exercise 4.2: Slice Arrays**
1. Extract rows 1 and 2, and columns 2 and 3:

In [19]:
subarray = array[0:2, 1:3]
print(subarray)

[[20 30]
 [50 60]]


2. Extract all elements from the last row:

In [20]:
print(array[-1, :])

[70 80 90]


3. Extract all elements from the second column:

In [21]:
print(array[:, 1])

[20 50 80]


### **Exercise Set 5: Arithmetic Operations**

#### **Exercise 5.1: Perform Arithmetic Operations**
1. Create two arrays:

In [22]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

In [23]:
# Perform the following operations:
# Add the arrays:
print(array1 + array2)

[5 7 9]


In [24]:
# Subtract the arrays:
print(array1 - array2)

[-3 -3 -3]


In [25]:
# Multiply the arrays element-wise:
print(array1 * array2)

[ 4 10 18]


In [26]:
# Divide the arrays element-wise:
print(array1 / array2)

[0.25 0.4  0.5 ]


#### **Exercise 5.2: Scalar Operations**
1. Multiply an array by a scalar:

In [27]:
print(array1 * 3)

[3 6 9]


2. Add a scalar to an array:

In [28]:
print(array1 + 5)

[6 7 8]


### **Exercise Set 6: Advanced Array Creation and Formatting**

#### **Exercise 6.1: Create Diagonal and Identity Matrices**
1. Create a 4x4 identity matrix:

In [29]:
identity_matrix = np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


2. Create a diagonal matrix with values `[10, 20, 30]`:

In [30]:
diagonal_matrix = np.diag([10, 20, 30])
print(diagonal_matrix)

[[10  0  0]
 [ 0 20  0]
 [ 0  0 30]]


#### **Exercise 6.2: Control Array Print Settings**
1. Set the precision to 3 decimal points:

In [31]:
np.set_printoptions(precision=3)
array = np.array([3.14159, 2.71828, 1.61803])
print(array)

[3.142 2.718 1.618]


2. Suppress scientific notation:

In [32]:
np.set_printoptions(suppress=True)
large_array = np.array([1e10, 1e-10])
print(large_array)

[1.e+10 1.e-10]


### **Challenge Exercises**
1. Create a 4x4 random array with values between 0 and 1, then round it to 2 decimal places.

In [33]:
random_array = np.random.random((4, 4))
rounded_array = np.round(random_array, 2)
print(rounded_array)

[[0.07 0.05 0.08 0.32]
 [0.04 0.99 0.92 0.54]
 [0.15 0.35 0.95 0.01]
 [0.84 0.1  0.73 0.76]]


2. Replace the diagonal of a 5x5 matrix of ones with values `[1, 2, 3, 4, 5]`.

In [34]:
matrix = np.ones((5, 5))
np.fill_diagonal(matrix, [1, 2, 3, 4, 5])
print(matrix)

[[1. 1. 1. 1. 1.]
 [1. 2. 1. 1. 1.]
 [1. 1. 3. 1. 1.]
 [1. 1. 1. 4. 1.]
 [1. 1. 1. 1. 5.]]


3. Create a checkerboard pattern (8x8) using `0` and `1`.

In [35]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
